#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, rgba32f) uniform image2D outputImage;

void main()
{
    ivec2 texelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec4 colorRGBA = vec4(0.0f, 0.0f, 0.0f, 1.0f);
    colorRGBA.x = float(texelCoords.x) / float(gl_NumWorkGroups.x);
    colorRGBA.y = float(texelCoords.y) / float(gl_NumWorkGroups.y);
    
    imageStore(outputImage, texelCoords, colorRGBA);
}